/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'berinle' at '8/27/15 1:28 PM' with Gradle 2.6
 *
 * @author berinle, @date 8/27/15 1:28 PM
 */
import java.util.concurrent.TimeUnit;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) throws Exception {
    	Library lib = new Library();
    	
    	while(true) {
    		lib.someLibraryMethod();
    		System.out.print(". ");
    		TimeUnit.SECONDS.sleep(1);    		
    	}    	
    }
}
